services:
  backend:
    build: ./backend
    volumes: 
      - ./backend/app:/app
    ports: 
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build: ./frontend/.
    volumes:
      - ./frontend/app:/home/user/app
    ports:
      - 8000:8000
